name: thingsboard-build-and-test

on:
  push:
    branches: [ release-4.2 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Verify Docker availability
        run: |
          docker --version
          docker info || true

      - name: Compile project
        run: mvn clean install -DskipTests

      - name: Build local Docker images for tests
        run: mvn clean install -Ddockerfile.skip=false

      - name: Docker image build verification
        run: docker image ls

      - name: Checkout to the test directory
        run: cd /msa/black-box-tests

      - name: Run black box tests without UI tests (unit tests)
        run: mvn clean install -DblackBoxTests.skip=false -DblackBoxTests.redisSsl=true